// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SeguimientoFacturacion.Infrastructure.Persistence;

#nullable disable

namespace SeguimientoFacturacion.Infrastructure
    .Persistence.Migrations;

[DbContext(typeof(SeguimientoDbContext))]
[Migration(
    "20260805235000_AmpliarEstructuraGlosasImportacion")]
partial class AmpliarEstructuraGlosasImportacion
{
}
