// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeguimientoFacturacion.Infrastructure.Persistence;

#nullable disable

namespace SeguimientoFacturacion.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SeguimientoDbContext))]
    [Migration("20260724195327_PermitirMovimientosAnualesSinFecha")]
    partial class PermitirMovimientosAnualesSinFecha
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.Catalogos.Aseguradora", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Aseguradoras", "facturacion");
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.Catalogos.Atencion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Atenciones", "facturacion");
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.Catalogos.Costo", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Costos", "facturacion");
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.Catalogos.Estado", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Estados", "facturacion");
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.Catalogos.Facturador", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Facturadores", "facturacion");
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.Catalogos.TipoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Sigla")
                        .IsUnique()
                        .HasDatabaseName("UX_TiposDocumento_Sigla");

                    b.ToTable("TiposDocumento", "facturacion");
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.Catalogos.TipoMovimiento", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TiposMovimiento", "facturacion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "NOTA CREDITO"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "ABONOS"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "GLOSA Y/O DEVOLUCION"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "CONCILIACION"
                        });
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.Factura", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("AseguradoraId")
                        .HasColumnType("int");

                    b.Property<int>("AtencionId")
                        .HasColumnType("int");

                    b.Property<int>("CostoId")
                        .HasColumnType("int");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<int>("FacturadorId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("FechaAdmision")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("FechaCreacionUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<DateOnly>("FechaFactura")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("FechaModificacionUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<DateOnly?>("FechaRadicacion")
                        .HasColumnType("date");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NumeroAdmision")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Prefijo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AseguradoraId")
                        .HasDatabaseName("IX_Facturas_AseguradoraId");

                    b.HasIndex("AtencionId");

                    b.HasIndex("CostoId");

                    b.HasIndex("EstadoId")
                        .HasDatabaseName("IX_Facturas_EstadoId");

                    b.HasIndex("FacturadorId")
                        .HasDatabaseName("IX_Facturas_FacturadorId");

                    b.HasIndex("FechaFactura")
                        .HasDatabaseName("IX_Facturas_FechaFactura");

                    b.HasIndex("TipoDocumentoId");

                    b.ToTable("Facturas", "facturacion");
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.Movimiento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FacturaId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("FechaCreacionUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<DateTimeOffset?>("FechaModificacionUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("NumeroNotaCredito")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TipoMovimientoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TipoMovimientoId")
                        .HasDatabaseName("IX_Movimientos_TipoMovimientoId");

                    b.HasIndex("FacturaId", "Anio", "Fecha")
                        .HasDatabaseName("IX_Movimientos_FacturaId_Anio_Fecha");

                    b.ToTable("Movimientos", "facturacion", t =>
                        {
                            t.HasCheckConstraint("CK_Movimientos_Anio", "[Anio] BETWEEN 2000 AND 9999");

                            t.HasCheckConstraint("CK_Movimientos_NumeroNotaCredito", "([TipoMovimientoId] = 1 AND [NumeroNotaCredito] IS NOT NULL AND [NumeroNotaCredito] > 0) OR ([TipoMovimientoId] <> 1 AND [NumeroNotaCredito] IS NULL)");

                            t.HasCheckConstraint("CK_Movimientos_Valor", "[Valor] >= 0");
                        });
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.Factura", b =>
                {
                    b.HasOne("SeguimientoFacturacion.Domain.Entities.Catalogos.Aseguradora", "Aseguradora")
                        .WithMany()
                        .HasForeignKey("AseguradoraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeguimientoFacturacion.Domain.Entities.Catalogos.Atencion", "Atencion")
                        .WithMany()
                        .HasForeignKey("AtencionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeguimientoFacturacion.Domain.Entities.Catalogos.Costo", "Costo")
                        .WithMany()
                        .HasForeignKey("CostoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeguimientoFacturacion.Domain.Entities.Catalogos.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeguimientoFacturacion.Domain.Entities.Catalogos.Facturador", "Facturador")
                        .WithMany()
                        .HasForeignKey("FacturadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeguimientoFacturacion.Domain.Entities.Catalogos.TipoDocumento", "TipoDocumento")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aseguradora");

                    b.Navigation("Atencion");

                    b.Navigation("Costo");

                    b.Navigation("Estado");

                    b.Navigation("Facturador");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.Movimiento", b =>
                {
                    b.HasOne("SeguimientoFacturacion.Domain.Entities.Factura", "Factura")
                        .WithMany("Movimientos")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeguimientoFacturacion.Domain.Entities.Catalogos.TipoMovimiento", "TipoMovimiento")
                        .WithMany()
                        .HasForeignKey("TipoMovimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Factura");

                    b.Navigation("TipoMovimiento");
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.Factura", b =>
                {
                    b.Navigation("Movimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
