// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SeguimientoFacturacion.Infrastructure.Persistence;

#nullable disable

namespace SeguimientoFacturacion.Infrastructure
    .Persistence.Migrations;

[DbContext(typeof(SeguimientoDbContext))]
[Migration(
    "20260806170000_RedistribuirPagosConAnticipos")]
partial class RedistribuirPagosConAnticipos
{
}
