// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeguimientoFacturacion.Infrastructure.Persistence;

#nullable disable

namespace SeguimientoFacturacion.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SeguimientoDbContext))]
    partial class SeguimientoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.AplicacionPago", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FacturaId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset>("FechaCreacionUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<DateTimeOffset?>("FechaModificacionUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("PagoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ValorAnticipo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorAplicado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorRecibido")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId")
                        .HasDatabaseName("IX_AplicacionesPago_FacturaId");

                    b.HasIndex("PagoId", "FacturaId")
                        .IsUnique()
                        .HasDatabaseName("UX_AplicacionesPago_Pago_Factura");

                    b.ToTable("AplicacionesPago", "cartera", t =>
                        {
                            t.HasCheckConstraint("CK_AplicacionesPago_Valores", "[ValorRecibido] > 0 AND [ValorAplicado] >= 0 AND [ValorAnticipo] >= 0 AND [ValorAplicado] + [ValorAnticipo] = [ValorRecibido]");
                        });
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.AplicacionPagoImportacionTemporal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FilaOrigen")
                        .HasColumnType("int");

                    b.Property<string>("HojaOrigen")
                        .IsRequired()
                        .HasMaxLength(31)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(31)");

                    b.Property<string>("IdentificadorFe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("PagoImportacionTemporalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Prefijo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("ValorAnticipo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorAplicado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorRecibido")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdentificadorFe")
                        .HasDatabaseName("IX_AplicacionesPagoTemporales_FE");

                    b.HasIndex("PagoImportacionTemporalId", "IdentificadorFe")
                        .IsUnique()
                        .HasDatabaseName("UX_AplicacionesPagoTemporales_Pago_FE");

                    b.HasIndex("PagoImportacionTemporalId", "HojaOrigen", "FilaOrigen")
                        .IsUnique()
                        .HasDatabaseName("UX_AplicacionesPagoTemporales_Pago_Hoja_Fila");

                    b.ToTable("AplicacionesPagoTemporales", "importacion", t =>
                        {
                            t.HasCheckConstraint("CK_AplicacionesPagoTemporales_FE", "[IdentificadorFe] = [Prefijo] + [NumeroFactura]");

                            t.HasCheckConstraint("CK_AplicacionesPagoTemporales_Fila", "[FilaOrigen] > 0");

                            t.HasCheckConstraint("CK_AplicacionesPagoTemporales_Valores", "[ValorRecibido] > 0 AND [ValorAplicado] >= 0 AND [ValorAnticipo] >= 0 AND [ValorAplicado] + [ValorAnticipo] = [ValorRecibido]");
                        });
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.Catalogos.Aseguradora", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("migracion-sistema");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("FechaCreacionUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTimeOffset?>("FechaModificacionUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Descripcion")
                        .HasDatabaseName("IX_Aseguradoras_Descripcion");

                    b.ToTable("Aseguradoras", "facturacion");
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.Catalogos.Atencion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Atenciones", "facturacion");
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.Catalogos.Costo", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Costos", "facturacion");
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.Catalogos.Estado", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Estados", "facturacion");
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.Catalogos.Facturador", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("migracion-sistema");

                    b.Property<DateTimeOffset>("FechaCreacionUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTimeOffset?>("FechaModificacionUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .HasDatabaseName("IX_Facturadores_Nombre");

                    b.ToTable("Facturadores", "facturacion");
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.Catalogos.TipoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Sigla")
                        .IsUnique()
                        .HasDatabaseName("UX_TiposDocumento_Sigla");

                    b.ToTable("TiposDocumento", "facturacion");
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.Catalogos.TipoMovimiento", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TiposMovimiento", "facturacion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "NOTA CREDITO"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "ABONOS"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "GLOSA Y/O DEVOLUCION"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "CONCILIACION"
                        });
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.Factura", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("AseguradoraId")
                        .HasColumnType("int");

                    b.Property<int>("AtencionId")
                        .HasColumnType("int");

                    b.Property<int>("CostoId")
                        .HasColumnType("int");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<int>("FacturadorId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("FechaAdmision")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("FechaCreacionUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<DateOnly>("FechaFactura")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("FechaModificacionUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<DateOnly?>("FechaRadicacion")
                        .HasColumnType("date");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NumeroAdmision")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Prefijo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("VersionFila")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("AseguradoraId")
                        .HasDatabaseName("IX_Facturas_AseguradoraId");

                    b.HasIndex("AtencionId");

                    b.HasIndex("CostoId");

                    b.HasIndex("EstadoId")
                        .HasDatabaseName("IX_Facturas_EstadoId");

                    b.HasIndex("FacturadorId")
                        .HasDatabaseName("IX_Facturas_FacturadorId");

                    b.HasIndex("FechaFactura")
                        .HasDatabaseName("IX_Facturas_FechaFactura");

                    b.HasIndex("TipoDocumentoId", "NumeroDocumento");

                    b.ToTable("Facturas", "facturacion");
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.FacturaImportacionTemporal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AseguradoraId")
                        .HasColumnType("int");

                    b.Property<int>("AtencionId")
                        .HasColumnType("int");

                    b.Property<int>("CostoId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<int>("FacturadorId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("FechaAdmision")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaFactura")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaRadicacion")
                        .HasColumnType("date");

                    b.Property<int>("FilaOrigen")
                        .HasColumnType("int");

                    b.Property<string>("HojaOrigen")
                        .IsRequired()
                        .HasMaxLength(31)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(31)");

                    b.Property<string>("IdentificadorFe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("LoteImportacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NumeroAdmision")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Prefijo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LoteImportacionId", "IdentificadorFe")
                        .HasDatabaseName("IX_FacturasTemporales_Lote_FE");

                    b.HasIndex("LoteImportacionId", "HojaOrigen", "FilaOrigen")
                        .IsUnique()
                        .HasDatabaseName("UX_FacturasTemporales_Lote_Hoja_Fila");

                    b.HasIndex("LoteImportacionId", "Prefijo", "Numero")
                        .HasDatabaseName("IX_FacturasTemporales_Lote_Prefijo_Numero");

                    b.ToTable("FacturasTemporales", "importacion", t =>
                        {
                            t.HasCheckConstraint("CK_FacturasTemporales_Catalogos", "[AseguradoraId] > 0 AND [TipoDocumentoId] > 0 AND [AtencionId] > 0 AND [CostoId] > 0 AND [EstadoId] > 0 AND [FacturadorId] > 0");

                            t.HasCheckConstraint("CK_FacturasTemporales_Fechas", "([FechaRadicacion] IS NULL OR [FechaRadicacion] >= [FechaFactura]) AND ([FechaAdmision] IS NULL OR [FechaAdmision] <= [FechaFactura])");

                            t.HasCheckConstraint("CK_FacturasTemporales_FilaOrigen", "[FilaOrigen] > 0");

                            t.HasCheckConstraint("CK_FacturasTemporales_Valor", "[Valor] > 0");
                        });
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.Glosa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("FacturaId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset>("FechaCreacionUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<DateOnly>("FechaGlosa")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("FechaModificacionUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<DateOnly?>("FechaRespuesta")
                        .HasColumnType("date");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("ValorAceptado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorGlosa")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("VersionFila")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("FechaGlosa")
                        .HasDatabaseName("IX_Glosas_FechaGlosa");

                    b.HasIndex("FacturaId", "Estado", "FechaGlosa")
                        .HasDatabaseName("IX_Glosas_Factura_Estado_Fecha");

                    b.HasIndex("FacturaId", "FechaGlosa", "ValorGlosa")
                        .IsUnique()
                        .HasDatabaseName("UX_Glosas_Factura_Fecha_Valor");

                    b.ToTable("Glosas", "facturacion", t =>
                        {
                            t.HasCheckConstraint("CK_Glosas_FechaRespuesta", "[FechaRespuesta] IS NULL OR [FechaRespuesta] >= [FechaGlosa]");

                            t.HasCheckConstraint("CK_Glosas_ValorAceptado", "[ValorAceptado] >= 0 AND [ValorAceptado] <= [ValorGlosa]");

                            t.HasCheckConstraint("CK_Glosas_ValorGlosa", "[ValorGlosa] > 0");
                        });
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.GlosaImportacionTemporal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AseguradoraId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaGlosa")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaRespuesta")
                        .HasColumnType("date");

                    b.Property<int>("FilaOrigen")
                        .HasColumnType("int");

                    b.Property<string>("HojaOrigen")
                        .IsRequired()
                        .HasMaxLength(31)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(31)");

                    b.Property<string>("IdentificadorFe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("LoteImportacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Prefijo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("ValorAceptado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorGlosa")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LoteImportacionId", "IdentificadorFe")
                        .HasDatabaseName("IX_GlosasTemporales_Lote_FE");

                    b.HasIndex("LoteImportacionId", "HojaOrigen", "FilaOrigen")
                        .IsUnique()
                        .HasDatabaseName("UX_GlosasTemporales_Lote_Hoja_Fila");

                    b.HasIndex("LoteImportacionId", "IdentificadorFe", "FechaGlosa", "ValorGlosa")
                        .IsUnique()
                        .HasDatabaseName("UX_GlosasTemporales_Lote_Factura_Fecha_Valor");

                    b.ToTable("GlosasTemporales", "importacion", t =>
                        {
                            t.HasCheckConstraint("CK_GlosasTemporales_Aseguradora", "[AseguradoraId] > 0");

                            t.HasCheckConstraint("CK_GlosasTemporales_Estado", "[Estado] IN (1, 2, 3, 4, 5)");

                            t.HasCheckConstraint("CK_GlosasTemporales_FE", "[IdentificadorFe] = [Prefijo] + [NumeroFactura]");

                            t.HasCheckConstraint("CK_GlosasTemporales_Fechas", "[FechaRespuesta] IS NULL OR [FechaRespuesta] >= [FechaGlosa]");

                            t.HasCheckConstraint("CK_GlosasTemporales_FilaOrigen", "[FilaOrigen] > 0");

                            t.HasCheckConstraint("CK_GlosasTemporales_Resolucion", "([Estado] = 1 AND [FechaRespuesta] IS NULL AND [ValorAceptado] = 0) OR ([Estado] = 2 AND [FechaRespuesta] IS NOT NULL AND [ValorAceptado] = 0) OR ([Estado] = 3 AND [FechaRespuesta] IS NOT NULL AND [ValorAceptado] > 0) OR ([Estado] = 4 AND [FechaRespuesta] IS NOT NULL AND [ValorAceptado] = 0) OR ([Estado] = 5 AND [FechaRespuesta] IS NOT NULL)");

                            t.HasCheckConstraint("CK_GlosasTemporales_Valor", "[ValorGlosa] > 0");

                            t.HasCheckConstraint("CK_GlosasTemporales_ValorAceptado", "[ValorAceptado] >= 0 AND [ValorAceptado] <= [ValorGlosa]");
                        });
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.InconsistenciaImportacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Columna")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EsDatoSensible")
                        .HasColumnType("bit");

                    b.Property<Guid>("LoteImportacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("NumeroFila")
                        .HasColumnType("int");

                    b.Property<int>("Severidad")
                        .HasColumnType("int");

                    b.Property<string>("ValorPresentado")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("LoteImportacionId", "Codigo")
                        .HasDatabaseName("IX_InconsistenciasImportacion_Lote_Codigo");

                    b.HasIndex("LoteImportacionId", "Severidad", "NumeroFila")
                        .HasDatabaseName("IX_InconsistenciasImportacion_Lote_Severidad_Fila");

                    b.ToTable("InconsistenciasImportacion", "importacion", t =>
                        {
                            t.HasCheckConstraint("CK_InconsistenciasImportacion_NumeroFila", "[NumeroFila] IS NULL OR [NumeroFila] > 0");
                        });
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.LoteImportacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConfirmadoPor")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DetalleResultado")
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("FechaAnalisisUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<DateTimeOffset?>("FechaConfirmacionUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<DateTimeOffset>("FechaCreacionUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<DateTimeOffset?>("FechaFinalizacionUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<DateTimeOffset?>("FechaInicioProcesamientoUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<DateTimeOffset?>("FechaModificacionUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<string>("HashArchivo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int>("TotalAdvertencias")
                        .HasColumnType("int");

                    b.Property<int>("TotalErrores")
                        .HasColumnType("int");

                    b.Property<int>("TotalFilas")
                        .HasColumnType("int");

                    b.Property<int>("TotalFilasConError")
                        .HasColumnType("int");

                    b.Property<int>("TotalFilasValidas")
                        .HasColumnType("int");

                    b.Property<byte[]>("VersionFila")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Estado", "FechaCreacionUtc")
                        .HasDatabaseName("IX_LotesImportacion_Estado_FechaCreacionUtc");

                    b.HasIndex("Tipo", "HashArchivo")
                        .HasDatabaseName("IX_LotesImportacion_Tipo_HashArchivo");

                    b.ToTable("LotesImportacion", "importacion", t =>
                        {
                            t.HasCheckConstraint("CK_LotesImportacion_Totales", "[TotalFilas] >= 0 AND [TotalFilasValidas] >= 0 AND [TotalFilasConError] >= 0 AND [TotalErrores] >= 0 AND [TotalAdvertencias] >= 0 AND [TotalFilasValidas] + [TotalFilasConError] = [TotalFilas] AND [TotalErrores] >= [TotalFilasConError]");
                        });
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.Movimiento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FacturaId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("FechaCreacionUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<DateTimeOffset?>("FechaModificacionUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NumeroNotaCredito")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TipoMovimientoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TipoMovimientoId")
                        .HasDatabaseName("IX_Movimientos_TipoMovimientoId");

                    b.HasIndex("FacturaId", "Anio", "Fecha")
                        .HasDatabaseName("IX_Movimientos_FacturaId_Anio_Fecha");

                    b.ToTable("Movimientos", "facturacion", t =>
                        {
                            t.HasCheckConstraint("CK_Movimientos_Anio", "[Anio] BETWEEN 2000 AND 9999");

                            t.HasCheckConstraint("CK_Movimientos_NumeroNotaCredito", "([TipoMovimientoId] = 1 AND NULLIF(LTRIM(RTRIM([NumeroNotaCredito])), '') IS NOT NULL) OR ([TipoMovimientoId] <> 1 AND [NumeroNotaCredito] IS NULL)");

                            t.HasCheckConstraint("CK_Movimientos_Valor", "[Valor] >= 0");
                        });
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.NotaFactura", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Anulada")
                        .HasColumnType("bit");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FacturaId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("FechaCreacionUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<DateTimeOffset?>("FechaModificacionUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<Guid?>("GlosaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("IX_NotasFactura_Fecha");

                    b.HasIndex("GlosaId")
                        .HasDatabaseName("IX_NotasFactura_GlosaId");

                    b.HasIndex("FacturaId", "Tipo", "Numero")
                        .IsUnique()
                        .HasDatabaseName("UX_NotasFactura_Factura_Tipo_Numero");

                    b.ToTable("NotasFactura", "facturacion", t =>
                        {
                            t.HasCheckConstraint("CK_NotasFactura_Anulacion", "([Anulada] = 0 AND [MotivoAnulacion] IS NULL) OR ([Anulada] = 1 AND NULLIF(LTRIM(RTRIM([MotivoAnulacion])), '') IS NOT NULL)");

                            t.HasCheckConstraint("CK_NotasFactura_Glosa", "([Tipo] = 1 AND [GlosaId] IS NOT NULL) OR ([Tipo] = 2 AND [GlosaId] IS NULL)");

                            t.HasCheckConstraint("CK_NotasFactura_Valor", "[Valor] > 0");
                        });
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.NotaFacturaImportacionTemporal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AseguradoraId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaNota")
                        .HasColumnType("date");

                    b.Property<int>("FilaOrigen")
                        .HasColumnType("int");

                    b.Property<Guid?>("GlosaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HojaOrigen")
                        .IsRequired()
                        .HasMaxLength(31)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(31)");

                    b.Property<string>("IdentificadorFe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("LoteImportacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NumeroNota")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Prefijo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorNota")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GlosaId")
                        .HasDatabaseName("IX_NotasFacturaTemporales_GlosaId");

                    b.HasIndex("LoteImportacionId", "IdentificadorFe")
                        .HasDatabaseName("IX_NotasFacturaTemporales_Lote_FE");

                    b.HasIndex("LoteImportacionId", "HojaOrigen", "FilaOrigen")
                        .IsUnique()
                        .HasDatabaseName("UX_NotasFacturaTemporales_Lote_Hoja_Fila");

                    b.HasIndex("LoteImportacionId", "IdentificadorFe", "Tipo", "NumeroNota")
                        .IsUnique()
                        .HasDatabaseName("UX_NotasFacturaTemporales_Lote_Factura_Tipo_Numero");

                    b.ToTable("NotasFacturaTemporales", "importacion", t =>
                        {
                            t.HasCheckConstraint("CK_NotasFacturaTemporales_Aseguradora", "[AseguradoraId] > 0");

                            t.HasCheckConstraint("CK_NotasFacturaTemporales_FE", "[IdentificadorFe] = [Prefijo] + [NumeroFactura]");

                            t.HasCheckConstraint("CK_NotasFacturaTemporales_FilaOrigen", "[FilaOrigen] > 0");

                            t.HasCheckConstraint("CK_NotasFacturaTemporales_Glosa", "([Tipo] = 1 AND [GlosaId] IS NOT NULL) OR ([Tipo] = 2 AND [GlosaId] IS NULL)");

                            t.HasCheckConstraint("CK_NotasFacturaTemporales_Tipo", "[Tipo] IN (1, 2)");

                            t.HasCheckConstraint("CK_NotasFacturaTemporales_Valor", "[ValorNota] > 0");
                        });
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTimeOffset>("FechaCreacionUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<DateTimeOffset?>("FechaModificacionUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("int");

                    b.Property<byte[]>("VersionFila")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasAlternateKey("TipoDocumentoId", "NumeroDocumento")
                        .HasName("AK_Pacientes_TipoDocumento_NumeroDocumento");

                    b.HasIndex("NombreCompleto")
                        .HasDatabaseName("IX_Pacientes_NombreCompleto");

                    b.ToTable("Pacientes", "facturacion");
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.Pago", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AseguradoraId")
                        .HasColumnType("int");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTimeOffset>("FechaCreacionUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<DateTimeOffset?>("FechaModificacionUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<DateOnly>("FechaPago")
                        .HasColumnType("date");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Notas")
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Recibo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("ReteIca")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Retencion")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorPagado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AseguradoraId", "FechaPago")
                        .HasDatabaseName("IX_Pagos_Aseguradora_FechaPago");

                    b.HasIndex("AseguradoraId", "Recibo")
                        .IsUnique()
                        .HasDatabaseName("UX_Pagos_Aseguradora_Recibo");

                    b.ToTable("Pagos", "cartera", t =>
                        {
                            t.HasCheckConstraint("CK_Pagos_ValorPagado", "[ValorPagado] > 0");

                            t.HasCheckConstraint("CK_Pagos_ValoresNoNegativos", "[Retencion] >= 0 AND [ReteIca] >= 0");
                        });
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.PagoImportacionTemporal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AseguradoraId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaPago")
                        .HasColumnType("date");

                    b.Property<Guid>("LoteImportacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notas")
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Recibo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("ReteIca")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Retencion")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorPagado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LoteImportacionId", "FechaPago")
                        .HasDatabaseName("IX_PagosTemporales_Lote_Fecha");

                    b.HasIndex("LoteImportacionId", "AseguradoraId", "Recibo")
                        .IsUnique()
                        .HasDatabaseName("UX_PagosTemporales_Lote_Aseguradora_Recibo");

                    b.ToTable("PagosTemporales", "importacion", t =>
                        {
                            t.HasCheckConstraint("CK_PagosTemporales_Aseguradora", "[AseguradoraId] > 0");

                            t.HasCheckConstraint("CK_PagosTemporales_ValorPagado", "[ValorPagado] > 0");

                            t.HasCheckConstraint("CK_PagosTemporales_Valores", "[Retencion] >= 0 AND [ReteIca] >= 0");
                        });
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.RegistroAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CorrelacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DatosAnterioresJson")
                        .HasMaxLength(20000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatosNuevosJson")
                        .HasMaxLength(20000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntidadId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTimeOffset>("FechaUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NombreEntidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TipoOperacion")
                        .HasColumnType("int");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelacionId")
                        .HasDatabaseName("IX_RegistrosAuditoria_CorrelacionId")
                        .HasFilter("[CorrelacionId] IS NOT NULL");

                    b.HasIndex("Usuario", "FechaUtc")
                        .HasDatabaseName("IX_RegistrosAuditoria_Usuario_FechaUtc");

                    b.HasIndex("NombreEntidad", "EntidadId", "FechaUtc")
                        .HasDatabaseName("IX_RegistrosAuditoria_Entidad_FechaUtc");

                    b.ToTable("RegistrosAuditoria", "auditoria");
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.AplicacionPago", b =>
                {
                    b.HasOne("SeguimientoFacturacion.Domain.Entities.Factura", "Factura")
                        .WithMany()
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeguimientoFacturacion.Domain.Entities.Pago", "Pago")
                        .WithMany("Aplicaciones")
                        .HasForeignKey("PagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Factura");

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.AplicacionPagoImportacionTemporal", b =>
                {
                    b.HasOne("SeguimientoFacturacion.Domain.Entities.PagoImportacionTemporal", "PagoImportacionTemporal")
                        .WithMany("Aplicaciones")
                        .HasForeignKey("PagoImportacionTemporalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PagoImportacionTemporal");
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.Factura", b =>
                {
                    b.HasOne("SeguimientoFacturacion.Domain.Entities.Catalogos.Aseguradora", "Aseguradora")
                        .WithMany()
                        .HasForeignKey("AseguradoraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeguimientoFacturacion.Domain.Entities.Catalogos.Atencion", "Atencion")
                        .WithMany()
                        .HasForeignKey("AtencionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeguimientoFacturacion.Domain.Entities.Catalogos.Costo", "Costo")
                        .WithMany()
                        .HasForeignKey("CostoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeguimientoFacturacion.Domain.Entities.Catalogos.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeguimientoFacturacion.Domain.Entities.Catalogos.Facturador", "Facturador")
                        .WithMany()
                        .HasForeignKey("FacturadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeguimientoFacturacion.Domain.Entities.Catalogos.TipoDocumento", "TipoDocumento")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeguimientoFacturacion.Domain.Entities.Paciente", null)
                        .WithMany()
                        .HasForeignKey("TipoDocumentoId", "NumeroDocumento")
                        .HasPrincipalKey("TipoDocumentoId", "NumeroDocumento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Facturas_Pacientes_Identificacion");

                    b.Navigation("Aseguradora");

                    b.Navigation("Atencion");

                    b.Navigation("Costo");

                    b.Navigation("Estado");

                    b.Navigation("Facturador");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.FacturaImportacionTemporal", b =>
                {
                    b.HasOne("SeguimientoFacturacion.Domain.Entities.LoteImportacion", "LoteImportacion")
                        .WithMany()
                        .HasForeignKey("LoteImportacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoteImportacion");
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.Glosa", b =>
                {
                    b.HasOne("SeguimientoFacturacion.Domain.Entities.Factura", "Factura")
                        .WithMany()
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.GlosaImportacionTemporal", b =>
                {
                    b.HasOne("SeguimientoFacturacion.Domain.Entities.LoteImportacion", "LoteImportacion")
                        .WithMany()
                        .HasForeignKey("LoteImportacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoteImportacion");
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.InconsistenciaImportacion", b =>
                {
                    b.HasOne("SeguimientoFacturacion.Domain.Entities.LoteImportacion", "LoteImportacion")
                        .WithMany()
                        .HasForeignKey("LoteImportacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoteImportacion");
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.Movimiento", b =>
                {
                    b.HasOne("SeguimientoFacturacion.Domain.Entities.Factura", "Factura")
                        .WithMany("Movimientos")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeguimientoFacturacion.Domain.Entities.Catalogos.TipoMovimiento", "TipoMovimiento")
                        .WithMany()
                        .HasForeignKey("TipoMovimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Factura");

                    b.Navigation("TipoMovimiento");
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.NotaFactura", b =>
                {
                    b.HasOne("SeguimientoFacturacion.Domain.Entities.Factura", "Factura")
                        .WithMany()
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeguimientoFacturacion.Domain.Entities.Glosa", "Glosa")
                        .WithMany()
                        .HasForeignKey("GlosaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Factura");

                    b.Navigation("Glosa");
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.NotaFacturaImportacionTemporal", b =>
                {
                    b.HasOne("SeguimientoFacturacion.Domain.Entities.Glosa", null)
                        .WithMany()
                        .HasForeignKey("GlosaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SeguimientoFacturacion.Domain.Entities.LoteImportacion", "LoteImportacion")
                        .WithMany()
                        .HasForeignKey("LoteImportacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoteImportacion");
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.Paciente", b =>
                {
                    b.HasOne("SeguimientoFacturacion.Domain.Entities.Catalogos.TipoDocumento", "TipoDocumento")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.Pago", b =>
                {
                    b.HasOne("SeguimientoFacturacion.Domain.Entities.Catalogos.Aseguradora", "Aseguradora")
                        .WithMany()
                        .HasForeignKey("AseguradoraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aseguradora");
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.PagoImportacionTemporal", b =>
                {
                    b.HasOne("SeguimientoFacturacion.Domain.Entities.LoteImportacion", "LoteImportacion")
                        .WithMany()
                        .HasForeignKey("LoteImportacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoteImportacion");
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.Factura", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.Pago", b =>
                {
                    b.Navigation("Aplicaciones");
                });

            modelBuilder.Entity("SeguimientoFacturacion.Domain.Entities.PagoImportacionTemporal", b =>
                {
                    b.Navigation("Aplicaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
